### ISSUE TITLE
로컬, 개발 phase에서는 github 없이 로그인을 가능하게 한다.

### ISSUE THREAD

**Issue by jayjaehunchoi** [The-Fellowship-of-the-matzip/mat.zip-back#149]
인증 쪽 코드에 조금 수정이 생기겠지만.

1. phase를 확인한다.
2. phase가 local이나 dev일경우 임의의 헤더에 user 테이블 id를 넣어 인증이 뚫리게끔 세팅한다. (토큰없이 순수 id 값만 넣어 개발이 되게끔 개발)
3. 라이브에서는 불가하다.

**Comment by beer-2000** [comment]
### How to solve
AuthenticationContext의 필드로 Member를 가지고 있는다.
또는 AuthenticationArgumentResolver에서 Repository를 가지고 조회 후 반환한다.
